<footer class="basic-footer">
<div class="container">
  <div class="row">
    <p>© Copyright 2018 HBL Asset Management Limited. All rights reserved.</p>
    <ul class="list-unstyled list-inline pull-left">
      <li>Toll-Free Helpline: 0800-24526</li>
      <li> | UAN: 111-425-262</li>
      <li> | Email: <a href="mailto:info@hblasset.com"> info@hblasset.com</a></li>
    </ul>
    <ul class="list-unstyled list-inline pull-right social-footer">
      <li><a href="https://www.facebook.com/HBLFunds/"><i class="icon icon-facebook"></i></a></li>
      <li><a href="https://twitter.com/hblfunds"><i class="icon icon-twitter-square"></i></a></li>
      <li><a href="https://pk.linkedin.com/in/hblfunds"><i class="icon icon-linkedin"></i></a></li>
      <li><a href="#"><i class="icon icon-sphere"></i></a></li>
    </ul>
  </div>
</div>
</footer>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="<?php echo base_url();?>js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="<?php echo base_url();?>js/vendor/jquery-3.2.1.min.js"></script>
   
    <script src="<?php echo base_url();?>js/plugins.js"></script>
    <script src="<?php echo base_url();?>js/main.js"></script>
    <script src="<?php echo base_url();?>js/vendor/bootstrap.min.js"></script>

    <script src="<?php echo base_url();?>js/vendor/bootstrap-datepicker.min.js"></script>

       <script type="text/javascript">
                      $('.datepicker').datepicker({
                        format: 'mm/dd/yyyy',
                        startDate: '-3d'
                      });
                      </script>

    <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
    <script>
        window.ga = function () {
            ga.q.push(arguments)
        };
        ga.q = [];
        ga.l = +new Date;
        ga('create', 'UA-XXXXX-Y', 'auto');
        ga('send', 'pageview')

    </script>
    <script src="https://www.google-analytics.com/analytics.js" async defer></script>
</body>

</html>
